In [13]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). 
# You can use the reshape method -- `.reshape()`


import numpy as np

a = np.array([[3, 5, 7], [2, 4, 6], [3, 6, 9], [2, 8, 10]])
print(a)

Newshape = a.reshape(2,3,2)
print("\n reshape a...\n", Newshape)

[[ 3  5  7]
 [ 2  4  6]
 [ 3  6  9]
 [ 2  8 10]]

 reshape a...
 [[[ 3  5]
  [ 7  2]
  [ 4  6]]

 [[ 3  6]
  [ 9  2]
  [ 8 10]]]


In [18]:
# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

import numpy as np
i = np.linspace(0, 20, num=6)
print("Array i...", i)


# 9. Make a Deep Copy of the above array

import copy 

dc = copy.deepcopy(i)
print("Deepcopy", dc)

Array i... [ 0.  4.  8. 12. 16. 20.]
Deepcopy [ 0.  4.  8. 12. 16. 20.]


In [20]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'...
#     ```python

import numpy as np 

a =  ([[25, 16]])           
b =  ([[11, 2], [13, 4]])
c =  ([[7, 81], [5, 6], [11, 12]])
            
newArray = np.concatenate((a,b,c))
print("Print new array", newArray)

Print new array [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [52]:
# 12. Sort 'newArray' in order into 'sortedArray'

import numpy as np 

a =  ([[25, 16]])           
b =  ([[11, 2], [13, 4]])
c =  ([[7, 81], [5, 6], [11, 12]])
            
newArray = np.concatenate((a,b,c))
print("Print new array", newArray)

SA = np.sort(newArray)
print("n\SA sorted....\n", SA)

print(SA.ndim)

Print new array [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
n\SA sorted....
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
2


In [70]:
# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray',
# so it has 2 dimensions with a size of 2, 3.

import numpy as np
SA = np.sort(newArray)
print("n\SA sorted....\n", SA)

reshapedArray = SA.reshape(2,2,3)
print("\nreshaped array...\n", reshapedArray)


# 14. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.,



B = ([ [16, 25, 2]],
     [11, 4, 13],
     [7, 81,  5],
     [6, 11, 12])
    
s, a, v, y = B
print("s =", s)
print("a =", a)
print("v =", v)
print("y =", y)
print("The data type of B", type(B))

    

n\SA sorted....
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshaped array...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
s = [[16, 25, 2]]
a = [11, 4, 13]
v = [7, 81, 5]
y = [6, 11, 12]
The data type of B <class 'tuple'>


In [8]:
# 15. Combined and sort the following arrays into one called 'comboArray' ...

import numpy as np 

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
        
comboArray = np.concatenate((one, two, three))
print("Print new array", comboArray)

CA = np.sort(comboArray)
print("n\SA sorted....\n", CA)

        

Print new array [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
n\SA sorted....
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [15]:
# 16. Take 'comboArray' and perform the following slicing activities:

import numpy as np 

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
        
comboArray = np.concatenate((one, two, three))
print("Print new array", comboArray)


#     - print sec1 - the 2nd element 

comboArray = np.concatenate((one, two, three))
print("Sec1- 2nd Element is..", comboArray[2])
        
#print sec2 - all elements from the 3rd element to the last
print("Sec2- Elements 3rd to last are..", comboArray[3:-1])

#print sec3 - all elements from the 4th to the 14th elements
print("Sec3- Elements 4th to 14th are..", comboArray[4:14])

#print sec4 - the last 6 elements
print("Sec4- last 6 Elements are..", comboArray[-7:-1])


#     - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print("Sec5 elements from #0 up to and including #15 are..", comboArray[0:-7])


#     - print sec6 - from #20 every even element to the end
print("Sec6 elements from #20 every even element to the end..", comboArray[-16::2])

#    - print sec7 - from the last element moving forward, every 5th element.
print("Sec7 from the last element moving forward, every 5th element...", comboArray[:-1:5])

Print new array [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
Sec1- 2nd Element is.. 12
Sec2- Elements 3rd to last are.. [13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6]
Sec3- Elements 4th to 14th are.. [14 15 16 17 20 21 22 23 24 25]
Sec4- last 6 Elements are.. [1 2 3 4 5 6]
Sec5 elements from #0 up to and including #15 are.. [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0]
Sec6 elements from #20 every even element to the end.. [20 22 24 26  0  2  4  6]
Sec7 from the last element moving forward, every 5th element... [10 15 22 27  4]


In [16]:

# 20. Using `Series`, create a `DataFrame` that looks like this:

#     | Ingredients | Quantity | Unit |
#     |----|----|----|
#     | Flour | 4 | cups |
#     | Milk | 1 | cup |
#     | Eggs | 2 | large |
#     | Spam | 1 | can |

#     Name: Dinner, dtype: object
            
    
    
import pandas as pd
    
Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = 'Ingredients')
Quantity = pd.Series([4,1,2,1], name = 'Quantity')
Unit = pd.Series(["cups", "cup", "large", "can"], name = 'Unit')
    
df = pd.concat([Ingredients,Quantity,Unit], axis=1)
print(df)
print("Name: Dinner, dtype: object")

            

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can
Name: Dinner, dtype: object


In [17]:
# 21. Take this data and create a DataFrame named studentData
#     ```Python
#         {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#             'Height': [5.1, 6.2, 5.1, 5.2],
#             'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#             'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#             'Age': [21, 23, 24, 21],
#             'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#             'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#         }
#     ```

import pandas as pd
    
Student_Name = pd.Series(['Jai', 'janusha', 'Gaurav', 'Anuj'], name = 'Students')
Height = pd.Series([5.1, 6.2, 5.1, 5.2], name = 'Height')
Qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name = 'Qualification')
address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name = 'address')
Age = pd.Series([21, 23, 24, 21], name = 'age')
Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name = 'pets')   
sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name = 'sport')   

df = pd.concat([Student_Name,Height,Qualification,address,Age,Pets,sport], axis=1)
print(df)
print("Name: StudentData, dtype: object")



  Students  Height Qualification  address  age        pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
Name: StudentData, dtype: object


In [8]:
# 22. Add a new column to the DataFrame with the following deserts:
#         ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

#     ```

import pandas as pd
    
Students = pd.Series(['Jai', 'janusha', 'Gaurav', 'Anuj'], name = 'Students')
Height = pd.Series([5.1, 6.2, 5.1, 5.2], name = 'Height')
Qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name = 'Qualification')
address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name = 'address')
Age = pd.Series([21, 23, 24, 21], name = 'age')
Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name = 'pets')   
sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name = 'sport')   
desert = pd.Series(["ice_cream", "Cashew_Fudge", "waffels", "Carrot_Halwa"], name = 'desert')

df = pd.concat([Students,Height,Qualification,address,Age,Pets,sport,desert], axis=1)
print(df)
print("Name: StudentData, dtype: object")

  Students  Height Qualification  address  age        pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

         desert  
0     ice_cream  
1  Cashew_Fudge  
2       waffels  
3  Carrot_Halwa  
Name: StudentData, dtype: object


In [24]:
# 23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

import pandas as pd

df = pd.concat([Students,Height,Qualification,address,Age,Pets,sport,desert], axis=1)

Sorted_df = df.sort_values(['Students', 'address'])
                    
print(Sorted_df, sorted)


  Students  Height Qualification  address  age        pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

         desert  
3  Carrot_Halwa  
2       waffels  
0     ice_cream  
1  Cashew_Fudge   <built-in function sorted>


In [27]:
# 24. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

#     ```python
#         df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

import pandas as pd
import numpy as np

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv(r'cows_and_goats.csv', sep='\t', encoding='utf-8')

In [30]:
# 25. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

import pandas as pd
import numpy as np

df = pd.DataFrame( {'Vegetable': ['Asparagus', 'Eggplant', 'Tomato'],
      'Color': ['green', 'purple', 'red'],
      'grain': ['rice', 'pasta', 'quinoa']})
       

print(df)
df.to_csv(r'myveggies.csv', sep='\t', encoding='utf-8')


# (B) Using Pandas, make a change to your CSV file:

import pandas as pd

New = df.sort_values(['grain'])
print(New)               

# save a copy with a different name.
      
df.to_csv(r'Sortedmygrains.csv', sep='\t', encoding='utf-8')                     

   Vegetable   Color   grain
0  Asparagus   green    rice
1   Eggplant  purple   pasta
2     Tomato     red  quinoa
   Vegetable   Color   grain
1   Eggplant  purple   pasta
2     Tomato     red  quinoa
0  Asparagus   green    rice
